<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <PackageId>IPLocate</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>0.1.0</Version>
    <Authors>Siyabonga Mngadi</Authors>
    <Description>Simple client for the IPLocate API</Description>
    <PackageTags>ip geolocation http client</PackageTags>
    <RepositoryUrl>https://github.com/siya-mngadi/IPLocate</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
